### PR TITLE
完成实训作业

### PR DESCRIPTION
**Pull request by WanAnUncommon**

### CODE REVIEW

**Comment by Jimmy385898** [comment]
Please create a new folder on the [homepage](https://github.com/Jimmy385898/springboothomework) to store your commit

**Comment by WanAnUncommon** [comment]
I created Training2 and Training3 folders, but some changes are in the original code, because some training can be easily implemented using the original code.

**Comment by WanAnUncommon** [comment]
> Please create a new folder on the [homepage](https://github.com/Jimmy385898/springboothomework) to store your commit

I created Training2 and Training3 folders, but some changes are in the original code, because some training can be easily implemented using the original code.

**Comment by Jimmy385898** [comment]
> > Please create a new folder on the [homepage](https://github.com/Jimmy385898/springboothomework) to store your commit
> 
> I created Training2 and Training3 folders, but some changes are in the original code, because some training can be easily implemented using the original code.

OK, I understand what you mean, I will merge your pr

**Pull request merged**
